mfs: Share should return temporary error
TESTLOCK.ZIP test 3 suggests (below) that the error code returned
from open due to a sharing issue should indicate a transient
condition, rather than a fatal one.

BEFORE
======
Test #3:
Open of "d:\TESTLOCK.TMP" for REPLACE was successful, handle=5
Wrote 128 bytes at offset 0 to handle 5.
File length is now 128
Open of "d:\TESTLOCK.TMP" for REPLACE failed, _doserrno=5=ACCESS_DENIED
ExtdErr=0=unknown
Class=13=UNKNOWN, Locus=1=UNKNOWN, Action=4=ABORT
This is NOT a retriable/sharing error.
ERROR: this should have been classified as a retriable/sharing error.
Closed d:\TESTLOCK.TMP
Test #3: FAILED!

AFTER
=====
Test #3:
Open of "d:\TESTLOCK.TMP" for REPLACE was successful, handle=5
Wrote 128 bytes at offset 0 to handle 5.
File length is now 128
Open of "d:\TESTLOCK.TMP" for REPLACE failed, _doserrno=33=LOCK_VIOLATION
This is a retriable/sharing error, which is normal here (but TLIB wouldn't
retry it)
Open of "d:\TESTLOCK.TMP" for APPEND failed, _doserrno=33=LOCK_VIOLATION
This is a retriable/sharing error, which is normal here (TLIB would display
"awaiting access...")
Open of "d:\TESTLOCK.TMP" for MODIFY failed, _doserrno=33=LOCK_VIOLATION
This is a retriable/sharing error, which is normal here (TLIB would display
"awaiting access...")
Open of "d:\TESTLOCK.TMP" for READ failed, _doserrno=33=LOCK_VIOLATION
This is a retriable/sharing error, which is normal here (TLIB would display
"awaiting access...")
Closed d:\TESTLOCK.TMP
Open of "d:\TESTLOCK.TMP" for READ was successful, handle=5
Closed d:\TESTLOCK.TMP
Test #3: Passed.