CI: Report FAIL of regex that doesn't match
If wishing to parse results for values we need to assert that the
regex matches first, else on non match we ERROR instead of FAIL.

2022-06-25T17:59:17.6924549Z ERROR: Test PP-DOS-GIT  INT21 disk info
2022-06-25T17:59:17.6925053Z ----------------------------------------------------------------------
2022-06-25T17:59:17.6925422Z Traceback (most recent call last):
2022-06-25T17:59:17.6925772Z   File "test/test_dos.py", line 4109, in test_int21_disk_info
2022-06-25T17:59:17.6926345Z     dfs_total = int(t.group(1))
2022-06-25T17:59:17.6926778Z AttributeError: 'NoneType' object has no attribute 'group'