Reapply "Reapply "ci: disable flatpak for now""
This reverts commit 7551505ffb390502acc9fa5bc365bfcce34ac221.

Flatpak fails again for unclear reasons:
```
Cloning into '/__w/dosemu2/dosemu2/.flatpak-builder/build/fluidsynth-1/test/manual'...
fatal: git upload-pack: not our ref 1c17a7ad072b2545ce944653afc88d6d3a3f044d
fatal: remote error: upload-pack: not our ref 1c17a7ad072b2545ce944653afc88d6d3a3f044d
fatal: Fetched in submodule path 'test/manual', but it did not contain 1c17a7ad072b2545ce944653afc88d6d3a3f044d. Direct fetching of that commit failed.
Error: module fluidsynth: Child process exited with code 128
Error: Build failed: Error: The process '/usr/bin/xvfb-run' failed with exit code 1
```