Fix bug where typing "xdosemu /path/that/doesnt/exist" gave the error message:
    ERROR: Cannot canonicalize path (Success)

Or, on occasions:

    ERROR: Cannot canonicalize path (Exec format error)

It turns out that I was using com_errno, instead of errno, after realpath().
In order to solve this, I got rid of the hacky:

    #define xxx com_xxx

And replaced all instances of xxx appropriately.


git-svn-id: https://dosemu.svn.sourceforge.net/svnroot/dosemu/trunk@233 7758b857-130e-0410-ab9c-d8735a528d18